[package]
name = "micro-gui"
version = "0.1.0"
authors = ["Ryan Kurte <ryankurte@gmail.com>"]

[features]
default = [ "sdl" ]
rgb24 = []

sdl = ["sdl2"]

[dependencies]


[dependencies.sdl2]
version = "0.30"
optional = true
default-features = false
features = ["image"]

